<?php
// Daiktuva: zmogiski, varijuoti lietuviski preku aprasymai + tvarkingi pavadinimai.
$items = array(
36 => array('Traktorius MTZ-82',
  'Patikimas MTZ-82, dirbęs ūkyje, tvarkinga hidraulika ir dokumentai.',
  'Parduodu MTZ-82, dirbo pas mane ūkyje. Technika paprasta ir patikima – užsiveda iš karto net ir šaltą rytą. Hidraulika tvarkinga, padangų likutis apie 70 proc. Naudojimo žymių yra, bet niekur nelaša ir nerūdija. Dokumentai tvarkingi, galima iškart pervadinti. Kaina šiek tiek derinama. Atvažiuokite į Kauno rajoną – parodysiu, kaip dirba.'),
37 => array('Traktorius Belarus 920',
  'Prižiūrėtas Belarus 920 su šilta kabina ir serviso istorija.',
  'Belarus 920 pirktas naujas ir prižiūrėtas pagal visus reglamentus. Tepalai keisti laiku, serviso lapeliai išsaugoti. Kabina šilta, šildymas veikia, sėdynė patogi ilgoms dienoms lauke. Priekinė ašis varoma – tinka tiek arimui, tiek transportui. Valandų kaip tokio amžiaus traktoriui nedaug. Parduodu, nes įsigijau galingesnį. Klauskite telefonu, viską papasakosiu.'),
38 => array('Plūgas dvivagis',
  'Dvivagis plūgas, paruoštas darbui, korpusai sveiki.',
  'Dvivagis plūgas, naudotas nedideliame ūkyje. Korpusai sveiki, noragai dar geri, žemę verčia tolygiai. Rėmas nelenktas, viskas suvirinta tvarkingai. Tinka MTZ klasės traktoriui. Galiu pakrauti, atvažiavus padėsiu užsidėti. Kaina fiksuota, bet rimtam žmogui visada susitariam.'),
39 => array('Kultivatorius 2,5 m',
  '2,5 m kultivatorius dirvai ruošti, dantys neseniai keisti.',
  'Kultivatorius 2,5 m pločio, tinka prieš sėją dirvą paruošti. Dantys neseniai keisti, spyruoklės stangrios. Sukabinimas standartinis trijų taškų. Laikytas po stogu, todėl rūdžių praktiškai nėra. Dirbo tik savo laukuose, niekur nenuomotas. Galima apžiūrėti vietoje Panevėžio rajone.'),
40 => array('Sėjamoji Amazone',
  'Amazone sėjamoji, tiksli sėjos norma, paruošta sezonui.',
  'Amazone sėjamoji, dirbusi keletą sezonų, bet visada laikyta angare. Sėjos norma reguliuojasi tiksliai, vamzdeliai švarūs, sėklų dėžė be įtrūkimų. Markeriai veikia, žarnos nesutrūkinėjusios. Pati mašina vokiška, todėl detalių rasti nesunku. Parduodu, nes keičiu plotus ir reikia platesnės. Daugiau klausimų – skambinkite.'),
41 => array('Šienapjovė rotacinė',
  'Rotacinė šienapjovė, peiliai aštrūs, pjauna tolygiai.',
  'Rotacinė šienapjovė, pjauna švariai ir greitai. Peiliai neseniai sukti, atsarginių pridėsiu. Diržai geri, guoliai tylūs. Naudota savo pievose, nė karto neužkliuvusi už akmenų. Kaina derinama rimtam pirkėjui. Marijampolės rajonas, galima atvykti apžiūrėti savaitgalį.'),
42 => array('Priekaba 2PTS-4',
  '2PTS-4 priekaba su vertimu į tris puses, stabdžiai tvarkingi.',
  'Priekaba 2PTS-4, verčia į tris puses, mechanizmas veikia sklandžiai. Bortai sveiki, dugnas nepradilęs, neseniai perdažyta. Padangos laiko orą, stabdžiai sureguliuoti. Naudota grūdams ir mėšlui vežti. Dokumentai yra, registruota. Stovi Kauno rajone, galima pažiūrėti bet kurią dieną.'),
43 => array('Akumuliatorinis gręžtuvas Bosch',
  'Bosch gręžtuvas su dviem akumuliatoriais ir krovikliu.',
  'Bosch akumuliatorinis gręžtuvas, naudotas namų remontui. Komplekte du akumuliatoriai ir kroviklis, abu laiko įkrovą gerai. Sukimo jėgos pakanka tiek medienai, tiek metalui. Griebtuvas neklimpsta, greičiai persijungia tvarkingai. Yra ir originali dėžė. Atiduodu pigiau, nes liko nenaudojamas po remonto. Vilniuje galima atsiimti vietoje.'),
44 => array('Kampinis šlifuoklis Makita',
  'Makita šlifuoklis 125 mm, veikia be priekaištų.',
  'Makita kampinis šlifuoklis, 125 mm diskui. Variklis traukia stipriai, jokio cypimo ar kibirkščiavimo. Naudotas nedaug, daugiausia namų reikmėms. Apsauga ir rankena vietoje, laidas sveikas. Pridėsiu kelis naujus diskus. Kaina maža, nes tiesiog liko be reikalo. Susitikti galiu Kaune.'),
45 => array('Betono maišyklė 140 L',
  '140 l betono maišyklė, variklis tylus, būgnas tvarkingas.',
  'Betono maišyklė, 140 litrų būgnas. Variklis užsiveda iš pirmo karto ir sukasi tolygiai. Vainikas ir pavara sveiki, jokio strigimo. Naudota statant savo namą, dabar tiesiog stovi garaže. Ratukai laiko, galima nesunkiai pervežti. Šiauliuose, atvažiuokite apžiūrėti – pademonstruosiu, kaip veikia.'),
46 => array('Mini ekskavatorius',
  'Mini ekskavatorius, kompaktiškas, tinka siauroms vietoms.',
  'Mini ekskavatorius, patogus dirbti ankštose vietose – kieme, tarp pastatų. Hidraulika sandari, nelaša, kaušas laikosi tvirtai. Vikšrai gumuoti, takelių negadina. Variklis dūmų nemeta, alyvos nevartoja. Naudotas savo sklypo darbams, ne nuomai. Dėl apžiūros ir bandymo skambinkite, suderinsim laiką Vilniuje.'),
47 => array('Grandininis pjūklas Husqvarna',
  'Husqvarna pjūklas malkoms, grandinė nauja.',
  'Husqvarna grandininis pjūklas, pjauna malkas kaip sviestą. Užsiveda lengvai, tuščioji eiga stabili. Grandinė neseniai keista, juosta dar gera. Tepimas veikia, oro filtras švarus. Pjoviau tik savo malkas, profesionaliai nevarginau. Pridėsiu raktą ir šiek tiek grandinės alyvos. Panevėžyje galima atsiimti.'),
48 => array('VW Passat B6 2.0 TDI',
  'Passat B6 2.0 TDI, ekonomiškas, su nauja technine apžiūra.',
  'Volkswagen Passat B6, 2.0 TDI. Variklis tamprus, kelyje suvartoja apie 5–6 litrus. Neseniai praėjo techninę, galioja dar ilgam. Keistas paskirstymo dirželio komplektas, yra čekiai. Salonas tvarkingas, nerūkyta. Yra smulkių lako įbrėžimų, viskas matosi nuotraukose. Skambinkite, jei rimtai domitės – parodysiu Vilniuje.'),
49 => array('Priekaba lengvajam automobiliui',
  'Lengva priekaba su tentu, registruota, su dokumentais.',
  'Priekaba lengvajam automobiliui, patogaus dydžio – telpa ir baldai, ir statybinės medžiagos. Su tentu, kuris dar sandarus. Apšvietimas veikia, jungtis tvarkinga. Padangos geros, ratai centruoti, kelyje nemėto. Registruota, dokumentai paruošti perrašymui. Kaune galima apžiūrėti ir iškart pasiimti.'),
50 => array('Šaldytuvas Samsung',
  'Samsung šaldytuvas su šaldikliu apačioje, tylus.',
  'Samsung šaldytuvas, dviejų kamerų, šaldiklis apačioje. Šaldo gerai, temperatūra laikosi stabili. No Frost, todėl ledo atitirpinti nereikia. Lentynos sveikos, durelės užsidaro sandariai. Veikia tyliai, naktį negirdėti. Parduodu, nes virtuvėje keičiu visą techniką. Šiauliuose, galiu padėti įkelti į mašiną.'),
51 => array('Skalbyklė Bosch',
  'Bosch skalbyklė 7 kg, gręžia tyliai, be gedimų.',
  'Bosch skalbyklė, 7 kg talpa. Visi režimai veikia, gręžimas tylus, nemėto. Guma sveika, kvapo nėra – po skalbimo visada palikdavau praviras dureles. Filtras valytas. Parduodu dėl persikraustymo, nebetelpa naujame bute. Kaune atvažiuokite pasiimti, pademonstruosiu veikiančią.'),
52 => array('Vejapjovė benzininė',
  'Benzininė vejapjovė su savaeige funkcija, pjauna švariai.',
  'Benzininė vejapjovė, savaeigė – pačiam stumti beveik nereikia. Variklis užsiveda nuo pirmo patraukimo. Peilis aštrus, žolę pjauna tolygiai, surinkimo dėžė sveika. Aukštis reguliuojamas keliais lygiais. Naudota tik savo kieme, žiemą laikyta sausai. Alytuje, skambinkite ir atvažiuokite išbandyti.'),
53 => array('Sofa-lova',
  'Patogi sofa-lova kasdieniam miegui, mechanizmas tvarkingas.',
  'Sofa-lova, tinka ir svetainei, ir kasdieniam miegui. Išsikloja lengvai, mechanizmas necypia ir nestringa. Audinys švarus, dėmių nėra, gyvūnų namuose nelaikėme. Viduje yra patalynės dėžė. Nedidelis naudojimo nusėdimas yra, bet sėdėti ir miegoti patogu. Vilniuje, galime padėti išnešti.'),
58 => array('Vaikiškas vežimėlis',
  'Universalus vežimėlis 2-in-1 su lopšiu ir sportine dalimi.',
  'Vaikiškas vežimėlis, universalus – su lopšiu naujagimiui ir sportine dalimi vyresniam. Ratai pripučiami, rieda tyliai, amortizacija minkšta. Stogelis platus, yra lietaus apsauga ir krepšys daiktams. Sulankstomas kompaktiškai, telpa į bagažinę. Naudotas su vienu vaiku, prižiūrėtas. Galiu nuvalyti ir parodyti visas dalis.'),
63 => array('Kombainas Claas',
  'Claas kombainas, paruoštas pjūčiai, hederis tvarkingas.',
  'Claas javų kombainas, dirbęs ūkyje, bet visada laikytas po stogu. Pjūčiai paruoštas – hederis sutvarkytas, peiliai geri, sietai švarūs. Variklis dirba ramiai, kabinoje kondicionierius veikia. Valandų yra, bet technika prižiūrėta ir niekada neapleista. Detales rasti nesunku. Rimtam pirkėjui kaina aptariama, klauskite.'),
64 => array('Lauko purkštuvas',
  'Pakabinamas lauko purkštuvas su tolygiu purškimu.',
  'Lauko purkštuvas, pakabinamas ant traktoriaus. Bakas be įtrūkimų, siurblys laiko slėgį, purškia tolygiai per visą plotį. Purkštukai švarūs, kelis atsarginius pridėsiu. Strėlė sulankstoma, transportuoti patogu. Naudotas savo laukuose, po darbo visada plautas. Galima apžiūrėti ir išbandyti su vandeniu.'),
65 => array('Šakių krautuvas',
  'Šakinis krautuvas, kelia tvarkingai, padangos geros.',
  'Šakių krautuvas, kelia ir leidžia sklandžiai, hidraulika nelaša. Stiebas tiesus, grandinės sutepamos, šakės nesulankstytos. Padangos dar geros, nepraslysta. Užsiveda lengvai, dirba tyliai. Naudotas sandėlyje, ne lauke, todėl mažai dėvėtas. Atvažiavę pamatysite, kaip dirba – suderinkim laiką.'),
66 => array('Traktoriaus padangos',
  'Traktoriaus padangų komplektas, protektorius gilus.',
  'Traktoriaus padangos, parduodu komplektu. Protektorius dar gilus, likutis apie 80 proc., guma neįtrūkusi. Laikytos sausai, saulėje neleidau sukietėti. Tinka MTZ klasės traktoriui. Galima ir poromis, susitarsim. Pakrauti padėsiu. Skambinkite, pasakysiu tikslius matmenis.'),
67 => array('Suvirinimo aparatas',
  'Inverterinis suvirinimo aparatas, lankas stabilus.',
  'Suvirinimo aparatas, inverterinis. Lankas užsidega lengvai ir laikosi stabiliai, net plonesnį metalą virina švariai. Srovė reguliuojama tolygiai. Laidai su gnybtais sveiki, kaukę pridėsiu. Naudotas namų ūkyje, ne gamyboje. Nešiojamas, nesunkus. Kaune galima atsiimti ir iš karto išbandyti.'),
68 => array('Generatorius 5 kW',
  '5 kW benzininis generatorius, paruoštas dingus elektrai.',
  'Benzininis generatorius, 5 kW – užtenka namams dingus elektrai: šaldytuvas, katilas, apšvietimas. Užsiveda patikimai, dirba tolygiai, įtampa stabili. Yra ir 230 V, ir 12 V išvadai. Naudotas retai, daugiausia stovėjo paruoštas atsargai. Alyva keista. Parodysiu veikiantį po apkrova.'),
69 => array('Statybiniai pastoliai',
  'Statybiniai pastoliai, stabilūs, su platformomis.',
  'Statybiniai pastoliai, surenkami greitai, laikosi stabiliai. Rėmai tiesūs, jungtys sveikos, platformos nelūžę. Aukštį galima reguliuoti pagal poreikį. Naudoti tinkuojant ir dažant namą, po to laikyti garaže. Komplektas pilnas, nieko netrūksta. Galiu padėti pakrauti, telpa į priekabą. Skambinkite dėl matmenų.'),
70 => array('Plytelių pjaustyklė',
  'Plytelių pjaustyklė su vandeniu, pjauna tiksliai.',
  'Plytelių pjaustyklė su vandeniu, pjauna tiksliai ir be skilimų. Diskas dar geras, variklis sukasi tvirtai. Stalas lygus, kreiptuvas tvirtinasi patikimai. Naudota klojant savo namo plyteles, po to nuplauta ir padėta. Tinka tiek sienų, tiek grindų plytelėms. Dėl apžiūros susiderinsim laiką – skambinkite.'),
71 => array('Audi A4 B8',
  'Audi A4 B8, tvarkingas, su serviso istorija.',
  'Audi A4 B8, prižiūrėtas ir tvarkingas. Variklis dirba ramiai, jokio pašalinio garso. Pavarų dėžė perjunginėja sklandžiai. Salonas švarus, sėdynių paviršiai be įplyšimų, nerūkyta. Keista alyva, filtrai, yra čekiai. Smulkmenų, kaip ir kiekvienam naudotam, yra – viską parodysiu gyvai. Skambinkite, suderinsim apžiūrą.'),
72 => array('Motoroleris',
  'Ekonomiškas motoroleris miestui, užsiveda iš karto.',
  'Motoroleris, patogus mieste – ekonomiškas ir vikrus. Užsiveda iš karto, variklis dirba tolygiai. Padangos geros, stabdžiai stabdo tvirtai. Yra daiktadėžė po sėdyne, telpa šalmas. Naudotas važinėti į darbą, prižiūrėtas. Dokumentai tvarkingi. Skambinkite – galima išbandyti.'),
73 => array('Elektrinė viryklė',
  'Elektrinė viryklė su orkaite, visos kaitvietės veikia.',
  'Elektrinė viryklė su orkaite. Visos keturios kaitvietės kaista tolygiai, orkaitė laiko temperatūrą. Stiklas sveikas, rankenėlės nesulūžę. Vidus švarus, prižiūrėta. Parduodu, nes virtuvėje perėjau prie indukcinės. Veikia be jokių priekaištų. Galima apžiūrėti ir pasiimti, padėsiu įkelti.'),
74 => array('Indaplovė Bosch',
  'Bosch indaplovė 60 cm, plauna švariai, tyli.',
  'Bosch indaplovė, 60 cm pločio. Plauna švariai, indai išdžiūsta, jokių dėmių. Visi režimai veikia, programų pasirinkimas platus. Krepšeliai sveiki, sandarinimo gumos geros, nelaša. Naudota namuose, kalkės valytos laiku. Tyli, todėl galima leisti ir naktį. Skambinkite dėl apžiūros.'),
75 => array('Dulkių siurblys',
  'Galingas dulkių siurblys be maišelio, filtrai plaunami.',
  'Dulkių siurblys, be maišelio – konteineris tiesiog išplaunamas. Trauka stipri, net įsisenėjusias dulkes iš kilimo ištraukia. Filtrai plaunami, pridėsiu atsarginį. Laidas susivynioja automatiškai, antgalių keli. Veikia tvarkingai, jokio perkaitimo. Atiduodu nebrangiai, nes pirkome galingesnį.'),
76 => array('Sodo baldų komplektas',
  'Sodo baldų komplektas: stalas ir kėdės, atsparūs orams.',
  'Sodo baldų komplektas – stalas ir kėdės. Medžiaga atspari orams, vasarą stovėjo lauke ir nieko jam nenutiko. Konstrukcija tvirta, nesisiūbuoja, kėdės laiko svorį. Pagalvėlės yra, audinys švarus. Sulankstomi, žiemą patogu pasidėti. Tinka terasai ar pavėsinei. Galiu padėti pakrauti.'),
77 => array('iPhone 12',
  'iPhone 12, baterijos talpa gera, su dėklu ir krovikliu.',
  'iPhone 12, veikia greitai ir sklandžiai. Baterijos būklė dar gera, dienai užtenka. Ekranas be įbrėžimų, nuo pat pradžių buvo po apsauginiu stiklu. Korpuse keli vos matomi naudojimo pėdsakai. Visos funkcijos veikia – kamera, veido atpažinimas, viskas. Pridėsiu dėklą ir kroviklį. Susitiksim, galėsite patikrinti.'),
78 => array('Žaidimų kompiuteris',
  'Žaidimų kompiuteris su vaizdo plokšte, traukia naujus žaidimus.',
  'Žaidimų kompiuteris, surinktas neseniai. Procesorius ir vaizdo plokštė traukia ir naujesnius žaidimus aukštais nustatymais. SSD diskas, todėl viskas kraunasi akimirksniu. Korpusas vėdinamas gerai, nekaista, dirba tyliai. Naudotas namuose, ne kasykloje. Galiu paleisti ir parodyti, kaip sukasi žaidimai. Skambinkite.'),
79 => array('Monitorius 27 colių',
  '27 colių monitorius, vaizdas ryškus, be defektų.',
  'Monitorius, 27 colių. Vaizdas ryškus, spalvos tikslios, žiūrėti malonu tiek dirbant, tiek žaidžiant. Nė vieno negyvo taško, dėmių nėra. Kojelė tvirta, aukštis reguliuojamas. Yra ir HDMI, ir DisplayPort jungtys. Kabelius pridėsiu. Naudotas namuose, prižiūrėtas. Galima atsiimti ir patikrinti vietoje.'),
80 => array('Vaikiškas dviratukas',
  'Vaikiškas dviratukas su pagalbiniais ratukais.',
  'Vaikiškas dviratukas, tinka pradedantiems. Su pagalbiniais ratukais, kuriuos lengva nuimti, kai vaikas išmoksta. Rėmas tvirtas, padangos laiko orą. Stabdžiai veikia, grandinė sutepta. Sėdynės ir vairo aukštis reguliuojamas, todėl tarnaus ne vieną sezoną. Dažai beveik be įbrėžimų. Galima apžiūrėti.'),
81 => array('Irklavimo treniruoklis',
  'Irklavimo treniruoklis namų treniruotėms, sulankstomas.',
  'Irklavimo treniruoklis, tinka treniruotis namuose. Pasipriešinimas reguliuojamas, ekranėlis rodo laiką ir tempą. Slankiojanti sėdynė juda tyliai ir tolygiai. Konstrukcija tvirta, laiko svorį stabiliai. Sulankstomas, todėl nedaug užima vietos. Pirktas su gerais ketinimais, bet realiai naudotas mažai. Atiduodu pigiau.'),
);

$ok = 0; $fail = 0;
foreach ($items as $id => $d) {
    $r = wp_update_post(array(
        'ID'           => $id,
        'post_title'   => $d[0],
        'post_excerpt' => $d[1],
        'post_content' => $d[2],
    ), true);
    if (is_wp_error($r) || $r === 0) {
        echo "FAIL id=$id : " . (is_wp_error($r) ? $r->get_error_message() : 'post 0') . "\n";
        $fail++;
    } else {
        $ok++;
    }
}
echo "ATNAUJINTA: $ok | KLAIDOS: $fail\n";
